{application,transactions_api,
    [{compile_env,
         [{transactions_api,['Elixir.TransactionsApiWeb.Gettext'],error},
          {transactions_api,[dev_routes],{ok,true}}]},
     {optional_applications,[]},
     {applications,
         [kernel,stdlib,elixir,logger,runtime_tools,phoenix,phoenix_ecto,
          ecto_sql,postgrex,phoenix_live_dashboard,swoosh,finch,
          telemetry_metrics,telemetry_poller,gettext,jason,dns_cluster,bandit,
          csv,plug,plug_cowboy]},
     {description,"transactions_api"},
     {modules,
         ['Elixir.TransactionsApi','Elixir.TransactionsApi 2',
          'Elixir.TransactionsApi.Application',
          'Elixir.TransactionsApi.CSVStatus','Elixir.TransactionsApi.Mailer',
          'Elixir.TransactionsApi.Repo','Elixir.TransactionsApi.Transactions',
          'Elixir.TransactionsApi.Transactions.Transaction',
          'Elixir.TransactionsApiWeb',
          'Elixir.TransactionsApiWeb.ChangesetJSON',
          'Elixir.TransactionsApiWeb.ChangesetJSON 2',
          'Elixir.TransactionsApiWeb.Endpoint',
          'Elixir.TransactionsApiWeb.Endpoint 2',
          'Elixir.TransactionsApiWeb.ErrorJSON',
          'Elixir.TransactionsApiWeb.FallbackController',
          'Elixir.TransactionsApiWeb.FallbackController 2',
          'Elixir.TransactionsApiWeb.Gettext',
          'Elixir.TransactionsApiWeb.Plugs.Authentication',
          'Elixir.TransactionsApiWeb.Plugs.Authentication 2',
          'Elixir.TransactionsApiWeb.Router',
          'Elixir.TransactionsApiWeb.Router 2',
          'Elixir.TransactionsApiWeb.Telemetry',
          'Elixir.TransactionsApiWeb.TransactionController',
          'Elixir.TransactionsApiWeb.TransactionController 2',
          'Elixir.TransactionsApiWeb.TransactionJSON',
          'Elixir.TransactionsApiWeb.TransactionJSON 2']},
     {registered,[]},
     {vsn,"0.1.0"},
     {mod,{'Elixir.TransactionsApi.Application',[]}}]}.
